image: node:16.0.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@12.0.2
    - npm install
    - npm run build:ci
  artifacts:
    paths:
      - dist
  only:
    - master
    - pages